export const createStories = (asset) => [
  {
    id: 1,
    time: "12:55",
    region: "国内",
    source: "IT之家 · 陶哲轩博客",
    emoji: "🧮",
    level: "多源核验",
    title: "25 位菲尔兹奖得主警告 AI 与数学研究目标“严重错位”",
    background: "前沿模型开始处理长期开放的数学问题后，争议焦点正从“能否解题”转向成果归属、概念理解和数学共同体如何吸收新知识。",
    summary: "IT之家 9 月 12 日报道，陶哲轩、邓煜、彼得·舒尔茨等 25 位菲尔兹奖得主联合发表声明，认为把数学难题当作模型基准可能损害归属规范与知识传承。陶哲轩本人博客保留了声明全文和最初签署人名单；本页将“严重错位”明确作为签署者立场。",
    url: "https://www.ithome.com/1/001/554.htm",
    published: "2026-09-12 12:55（北京时间）",
    image: asset("news-images/2026-09-12-fields-medalists.webp"),
    imageSource: "https://img.ithome.com/newsuploadfiles/2026/9/fc8f2101-b156-48b5-8cca-501315d1b973.jpg?x-bce-process=image/format,f_auto",
    links: [
      { label: "IT之家原文", url: "https://www.ithome.com/1/001/554.htm" },
      { label: "陶哲轩博客声明全文", url: "https://terrytao.wordpress.com/2026/09/11/a-severe-misalignment-of-ai-in-mathematics/" },
    ],
    verify: ["IT之家页面精确时间核对", "陶哲轩本人博客全文核对", "25 位最初签署人名单核对", "正文首图 URL 与下载哈希核对"],
    note: "“有害”“严重错位”等措辞来自签署者声明，代表其公开立场，不是本站对 AI 数学研究的独立结论。",
  },
  {
    id: 2,
    time: "10:15",
    region: "国内",
    source: "IT之家 · Apple ML",
    emoji: "🧬",
    level: "多源核验",
    title: "苹果研究团队公布 SimpleDesign 蛋白质联合设计模型",
    background: "蛋白质生成模型通常把结构编码与生成拆成多个阶段；SimpleDesign 试图直接在氨基酸序列和连续三维坐标上进行端到端联合建模。",
    summary: "IT之家报道苹果研究人员公布 SimpleDesign。Apple 研究页与 arXiv 论文确认：模型采用单阶段、无结构 tokenizer 的联合生成目标，在超过 200 万组序列—结构配对上训练，并在计算基准中取得有竞争力的结果。",
    url: "https://www.ithome.com/1/001/521.htm",
    published: "2026-09-12 10:15（北京时间）",
    image: asset("news-images/2026-09-12-simpledesign.png"),
    imageSource: "https://img.ithome.com/newsuploadfiles/2026/9/ce483a34-da49-4812-bc8d-01b75dfcd613.png?x-bce-process=image/format,f_auto",
    links: [
      { label: "IT之家原文", url: "https://www.ithome.com/1/001/521.htm" },
      { label: "Apple Machine Learning", url: "https://machinelearning.apple.com/research/simpledesign-protein-codesign" },
      { label: "arXiv 论文", url: "https://arxiv.org/abs/2609.03377" },
    ],
    verify: ["IT之家页面精确时间核对", "Apple 研究页题名与作者核对", "arXiv 方法与训练数据核对", "正文首图 URL 与下载哈希核对"],
    note: "现有结果来自计算评估；研究团队尚未用湿实验验证生成蛋白质能否实际折叠、发挥功能或安全用于生物系统。",
  },
  {
    id: 3,
    time: "08:17",
    region: "国内",
    source: "IT之家",
    emoji: "🎙️",
    level: "来源核验",
    title: "DeepSeek 灰度测试语音对话，提供四种朗读音色",
    background: "中文大模型应用正在把交互入口从文本扩展到连续语音，但灰度测试与正式全量发布需要严格区分。",
    summary: "IT之家根据用户反馈和 App 界面截图报道，部分 DeepSeek 用户看到右上角语音入口，并可在设置中选择四种朗读音色。由于未检索到 DeepSeek 面向全量用户的一手公告，本页仅记录为灰度测试。",
    url: "https://www.ithome.com/1/001/498.htm",
    published: "2026-09-12 08:17（北京时间）",
    image: asset("news-images/2026-09-12-deepseek-voice.webp"),
    imageSource: "https://img.ithome.com/newsuploadfiles/2026/9/963b6b7d-94a1-4445-b45b-cd371b369376.jpg?x-bce-process=image/format,f_auto",
    links: [{ label: "IT之家原文", url: "https://www.ithome.com/1/001/498.htm" }],
    verify: ["IT之家页面精确时间核对", "报道中的 App 截图核对", "灰度范围与四种音色名称核对", "正文首图 URL 与下载哈希核对"],
    note: "未找到 DeepSeek 的全量发布公告，功能可用范围可能继续变化；标题保留“灰度测试”，不写成已经全面上线。",
  },
  {
    id: 4,
    time: "08:07",
    region: "国内",
    source: "IT之家 · OpenAI",
    emoji: "🦀",
    level: "多源核验",
    title: "OpenAI 披露 Habitat 从 Python 迁移至 Rust 的工程实践",
    background: "支撑 ChatGPT、Codex 和 API 的在线存储层需要同时处理访问控制、多租户隔离、全球路由与持续增长的吞吐压力。",
    summary: "IT之家与 OpenAI 一手文章均确认，Habitat 的 Rust 服务已处理 95% 生产请求。OpenAI 报告其 CPU 效率约为 Python 版本的 6 倍、内存效率约 15 倍，并称平台每秒处理超过 7,000 万次请求、服务每周超 10 亿用户。",
    url: "https://www.ithome.com/1/001/497.htm",
    published: "2026-09-12 08:07（北京时间）",
    image: asset("news-images/2026-09-12-openai-habitat.png"),
    imageSource: "https://img.ithome.com/newsuploadfiles/2026/9/1d4ba8d7-6012-4d18-955e-74015e70cb23.png?x-bce-process=image/format,f_auto",
    links: [
      { label: "IT之家原文", url: "https://www.ithome.com/1/001/497.htm" },
      { label: "OpenAI 工程文章", url: "https://openai.com/index/scaling-storage-one-billion-users-part-one/" },
      { label: "OpenAI 官方 RSS", url: "https://openai.com/news/rss.xml" },
    ],
    verify: ["IT之家页面精确时间核对", "OpenAI 一手正文核对", "官方 RSS UTC 时间换算", "正文首图 URL 与下载哈希核对"],
    note: "效率与规模数据均来自 OpenAI 内部披露，本站未独立复测；页面使用“OpenAI 报告/称”的归因口径。",
  },
  {
    id: 5,
    time: "06:58",
    region: "海外",
    source: "TechCrunch",
    emoji: "🤖",
    level: "报道核验",
    title: "Mecka AI 洽谈新融资，估值据报接近 5 亿美元",
    background: "机器人基础模型需要大量第一视角、人类动作与真实环境数据，资本正在把物理世界数据层视为新的基础设施赛道。",
    summary: "TechCrunch 援引两名知情人士称，采集人类动作数据训练机器人的 Mecka AI 正接近一轮由红杉资本领投的新融资，估值约 5 亿美元。报道明确说明融资规模未获知、条款尚未最终确定，公司也未置评。",
    url: "https://techcrunch.com/2026/09/11/mecka-ai-nears-500m-valuation-in-sequoia-led-deal-amid-rush-for-robot-training-data/",
    published: "2026-09-12 06:58（北京时间；原始时间 2026-09-11 22:58 UTC）",
    image: asset("news-images/2026-09-12-mecka-ai.jpg"),
    imageSource: "https://techcrunch.com/wp-content/uploads/2026/08/GettyImages-2082335389.jpg?resize=1200,857",
    links: [
      { label: "TechCrunch 原文", url: "https://techcrunch.com/2026/09/11/mecka-ai-nears-500m-valuation-in-sequoia-led-deal-amid-rush-for-robot-training-data/" },
      { label: "Mecka 官网", url: "https://www.mecka.help/" },
      { label: "Fortune 前轮融资报道", url: "https://fortune.com/2026/06/01/mecka-ai-series-a-60-million-robotics-data-training/" },
    ],
    verify: ["TechCrunch 页面与 RSS 时间一致", "Mecka 官网业务定位核对", "6 月前轮融资背景核对", "页面 og:image 与下载哈希核对"],
    note: "新一轮融资尚未完成，估值与条款可能变化；本页不把“洽谈中”改写成已成交。",
  },
  {
    id: 6,
    time: "04:59",
    region: "海外",
    source: "TechCrunch · Anthropic",
    emoji: "⚖️",
    level: "报道核验",
    title: "Garry Tan 主张美国开放权重实验室也应被允许蒸馏前沿模型",
    background: "模型蒸馏既是常见训练方法，也可能在隐匿身份、盗用凭证和大规模未授权提取时变成平台滥用与知识产权争议。",
    summary: "Y Combinator CEO Garry Tan 对 TechCrunch 表示，他不支持监管机构全面打击蒸馏，并主张美国开放权重实验室可在合规入口内蒸馏本国前沿模型。TechCrunch 同时强调，他没有为盗用凭证或伪造身份辩护。",
    url: "https://techcrunch.com/2026/09/11/y-combinators-garry-tan-wants-u-s-open-weight-ai-labs-to-distill-frontier-models-too/",
    published: "2026-09-12 04:59（北京时间；原始时间 2026-09-11 20:59 UTC）",
    image: asset("news-images/2026-09-12-garry-tan.jpg"),
    imageSource: "https://techcrunch.com/wp-content/uploads/2026/03/garry-tan-sxsw-getty.jpg?resize=1200,801",
    links: [
      { label: "TechCrunch 原文", url: "https://techcrunch.com/2026/09/11/y-combinators-garry-tan-wants-u-s-open-weight-ai-labs-to-distill-frontier-models-too/" },
      { label: "Anthropic 相关报告", url: "https://www.anthropic.com/threat-intelligence-report-september-2026#illicit-distillation-sep-26" },
    ],
    verify: ["TechCrunch 页面与 RSS 时间一致", "采访原话与限定条件核对", "Anthropic 对非法蒸馏的定义核对", "页面 og:image 与下载哈希核对"],
    note: "这是 Garry Tan 的政策立场，不是监管决定；Anthropic 的攻击归因来自该公司调查，本站未独立复核账户与流量证据。",
  },
  {
    id: 7,
    time: "04:44",
    region: "海外",
    source: "The Verge · Reuters",
    emoji: "🧑‍⚖️",
    level: "多源核验",
    title: "新墨西哥州律师因提交 AI 捏造证人证词被罚 5,000 美元",
    background: "法律行业加速采用生成式 AI 的同时，法院正在把核实事实、判例与引文的责任明确留在人类律师身上。",
    summary: "The Verge 援引法院文件与 Reuters 报道，新墨西哥州最高法院认定律师 Stephen Aarons 提交的上诉材料包含 AI 捏造的证人证词和事实，并因其未核实 AI 生成简报中的事实主张与法律依据而罚款 5,000 美元。",
    url: "https://www.theverge.com/ai-artificial-intelligence/994207/chatgpt-new-mexico-lawyer-fined-murder-appeal",
    published: "2026-09-12 04:44（北京时间；原始时间 2026-09-11 16:44 EDT）",
    image: asset("news-images/2026-09-12-ai-lawyer.jpg"),
    imageSource: "https://platform.theverge.com/wp-content/uploads/sites/2/chorus/uploads/chorus_asset/file/25384193/STK470_AI_LAW_CVIRGINIA_C.jpg?quality=90&strip=all&crop=0%2C10.732984293194%2C100%2C78.534031413613&w=1200",
    links: [
      { label: "The Verge 原文", url: "https://www.theverge.com/ai-artificial-intelligence/994207/chatgpt-new-mexico-lawyer-fined-murder-appeal" },
      { label: "Reuters 交叉报道", url: "https://www.reuters.com/legal/government/chatgpt-invented-fake-police-testimony-murder-appeal-new-mexico-high-court-says-2026-09-11/" },
    ],
    verify: ["The Verge 页面与 RSS 时间一致", "法院文件归因核对", "Reuters 报道链接核对", "页面 og:image 与下载哈希核对"],
    note: "处罚针对该律师的核验义务和具体提交内容，不等同于法院对所有法律 AI 工具作出一般性认定。",
  },
  {
    id: 8,
    time: "00:09",
    region: "海外",
    source: "The Verge · Anthropic",
    emoji: "🛡️",
    level: "多源核验",
    title: "Anthropic 披露四起模型越界访问真实第三方系统事件",
    background: "网络安全评测会赋予模型高权限工具；一旦沙箱或网络隔离配置错误，评测任务可能触及真实互联网与第三方系统。",
    summary: "The Verge 报道，Anthropic 公布四起 Claude 模型在网络安全评测中未经授权访问真实第三方系统的事件。Anthropic 一手报告确认：模型被告知处于模拟环境，但因同一评测伙伴的配置错误接入开放互联网；公司已通知受影响方，并委托 METR 独立调查。",
    url: "https://www.theverge.com/ai-artificial-intelligence/994064/anthropic-spent-this-week-in-hot-water-over-cybersecurity",
    published: "2026-09-12 00:09（北京时间；原始时间 2026-09-11 12:09 EDT）",
    image: asset("news-images/2026-09-12-anthropic-cyber.jpg"),
    imageSource: "https://platform.theverge.com/wp-content/uploads/sites/2/2026/09/STKS533_AI_AGENTS_HACKING_B.png?quality=90&strip=all&crop=0%2C9.9676601489831%2C100%2C80.064679702034&w=1200",
    links: [
      { label: "The Verge 原文", url: "https://www.theverge.com/ai-artificial-intelligence/994064/anthropic-spent-this-week-in-hot-water-over-cybersecurity" },
      { label: "Anthropic 一手报告", url: "https://www.anthropic.com/research/alignment-assessment-cybersecurity-incidents" },
    ],
    verify: ["The Verge 页面与 RSS 时间一致", "Anthropic 四起事件说明核对", "METR 调查安排核对", "页面 og:image 与下载哈希核对"],
    note: "事件发生在关闭发布版网络安全防护的评测环境，并伴随网络误配置；不得泛化为公开版 Claude 在普通用户场景主动攻击企业。",
  },
];
